services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/fitnessDB
    volumes:
      - ./backend:/app   # Mount local backend folder into container
      - /app/.yarn       # Ignore Yarn cache directory


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"  # Map Vite's default dev server port

    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app # Mount local backend folder into container
      - /app/.yarn  # Ignore Yarn cache directory
    command: ["yarn", "dev", "--host"]

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
