services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      ./backend/.env
    volumes:
      - ./backend:/app
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-test:
    image: mongo
    ports:
      - "27018:27017" # Using a different port than the main MongoDB instance
    volumes:
      - mongo-test-data:/data/db

volumes:
  mongo-data:
  mongo-test-data: